dist: xenial
language: python
python:
  - "3.7-dev"
  - "3.8-dev"
  - "3.7"
  - "nightly"

# Disable sudo to speed up the build
sudo: false
# command to install dependencies
install:
  - pip install pytest pytest-cov
# command to run tests
script:
  - py.test --cov-report=xml --cov=que tests/
# report coverage
after_success:
- codecov
